# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-23 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wechat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('appid', models.CharField(max_length=18, unique=True)),
                ('secret', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=191)),
                ('encoding_aes_key', models.CharField(max_length=43)),
            ],
            options={
                'verbose_name': '微信',
                'verbose_name_plural': '微信',
                'db_table': 'wechat',
            },
        ),
        migrations.CreateModel(
            name='WechatMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('click', 'click'), ('view', 'view'), ('scancode_push', 'scancode_push'), ('scancode_waitmsg', 'scancode_waitmsg'), ('pic_sysphoto', 'pic_sysphoto'), ('pic_photo_or_album', 'pic_photo_or_album'), ('pic_weixin', 'pic_weixin'), ('location_select', 'location_select'), ('media_id', 'media_id'), ('view_limited', 'view_limited'), ('miniprogram', 'miniprogram')], max_length=18)),
                ('key', models.CharField(blank=True, max_length=128, null=True)),
                ('media_id', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.CharField(blank=True, max_length=191, null=True)),
                ('pagepath', models.CharField(blank=True, max_length=191, null=True)),
                ('appid', models.CharField(blank=True, max_length=32, null=True)),
                ('wechat_appid', models.CharField(max_length=18)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wechat_django.WechatMenu')),
            ],
            options={
                'verbose_name': '微信',
                'verbose_name_plural': '微信',
                'db_table': 'wechat_menu',
            },
        ),
    ]
