# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-25 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechatmenu',
            options={'ordering': ['order'], 'verbose_name': '微信', 'verbose_name_plural': '微信'},
        ),
        migrations.AlterField(
            model_name='wechatmenu',
            name='type',
            field=models.CharField(blank=True, choices=[(None, None), ('click', 'click'), ('view', 'view'), ('scancode_push', 'scancode_push'), ('scancode_waitmsg', 'scancode_waitmsg'), ('pic_sysphoto', 'pic_sysphoto'), ('pic_photo_or_album', 'pic_photo_or_album'), ('pic_weixin', 'pic_weixin'), ('location_select', 'location_select'), ('media_id', 'media_id'), ('view_limited', 'view_limited'), ('miniprogram', 'miniprogram')], max_length=18, null=True),
        ),
    ]
