# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-28 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0002_auto_20170825_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechat',
            name='qcode',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='wechat',
            name='service_type',
            field=models.IntegerField(choices=[(0, '测试号'), (1, '订阅号'), (2, '升级后的订阅号'), (3, '服务号')], default=1),
        ),
    ]
