# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-28 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0003_auto_20170828_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64, unique=True)),
                ('unionid', models.CharField(blank=True, max_length=64, null=True)),
                ('nickname', models.CharField(blank=True, max_length=191)),
                ('province', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=32)),
                ('headimgurl', models.CharField(max_length=191)),
                ('privilege', jsonfield.fields.JSONField(default=dict)),
                ('wechat_appid', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name': '微信',
                'verbose_name_plural': '微信',
                'db_table': 'wechat_user',
            },
        ),
    ]
