# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0004_wechatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechat',
            name='redirect_uri',
            field=models.CharField(default=None, max_length=191, blank=True, null=True),
        ),
    ]
