# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_django', '0005_wechat_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='groupid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='remark',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='subscribe',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='subscribe_time',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wechat',
            name='redirect_uri',
            field=models.CharField(default=None, max_length=191),
        ),
    ]
